# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UK Rasch User Group
email: chris.wheadon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The website for the annual UK Rasch Day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rasch.org.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
paginate: 2

gems:
  - jekyll-paginate
  - github-pages
